num_iters: 10000

base_measure_params:
  alpha: 1
  beta: 1

concentration:
  value: 1.0
  
  prior:
    shape: 1.0
    rate: 0.001

density: pyclone_beta_binomial

beta_binomial_precision_params:
  value: 1000

  prior:
    shape: 1.0
    rate: 0.0001

  proposal:
    precision: 0.01

working_dir: /Users/matteo/Lavoro/KCL/Clonal

trace_dir: trace

samples:
  TCGA-CV-5444:
    mutations_file: Pyclone/TCGA-CV-5444.yaml

    tumour_content:
      value: 0.37

    error_rate: 0.001

